import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  previewContainer: {
    height: 180,
    margin: 16,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  wallpaperPreview: {
    flex: 1,
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  controlPanel: {
    flex: 1,
    paddingHorizontal: 16,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  stickyButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingVertical: 20,
    paddingBottom: 34,
    backgroundColor: 'rgba(28, 28, 30, 0.98)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
  },
  section: {
    marginBottom: 16,
  },
  colorInfoContainer: {
    marginTop: 8,
  },
  generateButton: {
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  generateButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
  },
  presetSection: {
    marginTop: 10,
    marginBottom: 16,
  },
  presetColorsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    width: '100%',
  },
  presetColorBox: {
    width: 40,
    height: 40,
    borderRadius: 20,
    margin: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  selectedPresetColor: {
    transform: [{ scale: 1.1 }],
  },
  colorPicker: {
    height: 250,
    width: '100%',
  },
  colorPickerContainer: {
    position: 'relative',
    borderRadius: 8,
    overflow: 'hidden',
    padding: 10,
  },
  toastContainer: {
    backgroundColor: 'rgba(28, 28, 30, 0.95)',
    minHeight: 100,
    margin: 11,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
  },
  toastText: {
    color: 'white',
    fontSize: 14,
    lineHeight: 20,
    flex: 1,
  },
  toastSuccessBorder: {
    borderColor: 'rgba(76, 175, 80, 0.3)',
  },
  toastErrorBorder: {
    borderColor: 'rgba(244, 67, 54, 0.3)',
  },
  toastInfoBorder: {
    borderColor: 'rgba(33, 150, 243, 0.3)',
  },
  rgbInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    textAlign: 'center',
  },
  colorInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  colorLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 8,
    minWidth: 40,
  },
  colorInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'monospace',
    marginRight: 8,
  },
  rgbInputs: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    gap: 4,
  },
  copyButton: {
    height: 40,
    width: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0,
  },
  copyButtonIcon: {
    fontSize: 16,
  },
  colorPickerApplyButton: {
    height: 40,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    marginTop: 20,
    marginBottom: 5,
    marginHorizontal: 16,
    alignSelf: 'center',
    paddingHorizontal: 20,
  },
  colorPickerApplyText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  previewOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 20,
    pointerEvents: 'box-none',
  },
  previewResolutionContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  previewResolutionInfo: {
    alignItems: 'center',
  },
  previewResolutionText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#FFFFFF',
    marginBottom: 2,
    fontWeight: '500',
  },
  hiddenOverflow: {
    overflow: 'hidden',
  },
});
